fkirc/attranslate

- sample-scripts/android/app/src/main/res/values-es/strings.xml
- sample-scripts/android_to_ios.sh
- sample-scripts/flutter.sh
- sample-scripts/flutter/lib/l10n/intl_de.arb
- sample-scripts/flutter/lib/l10n/intl_es.arb
- sample-scripts/flutter/lib/l10n/intl_messages.arb
- sample-scripts/ios/Localizable/es.lproj/Localizable.strings
- src/file-formats/android-xml/android-xml.ts
- src/file-formats/android-xml/xml-write.ts
- src/file-formats/common/json-common.ts
- src/file-formats/common/manual-review.ts
- src/file-formats/common/parse-utils.ts
- src/file-formats/flutter-arb/flutter-arb.ts
- src/file-formats/ios-strings/ios-read.ts
- src/file-formats/ios-strings/ios-write.ts
- test/e2e/invalid-files.test.ts
Specifics depend on the file-formats
> Manual Reviews

- .github/workflows/ci.yml
- README.md
- test/e2e/invalid-service-configs.test.ts
- test/test-util/test-util.ts
Test on both macOS and Ubuntu.
> Test Matrix

- sample-scripts/yaml/attranslate-cache_from-en_to-yaml_src-en_ecommerce.yml.json
- sample-scripts/yaml/de_ecommerce.yml
- sample-scripts/yaml/en_ecommerce.yml
- sample-scripts/yaml/es_ecommerce.yml
- src/file-formats/yaml/yaml-generic.ts
- src/file-formats/yaml/yaml-manipulation.ts
- test-assets/yml/country_array.yml
- test-assets/yml/country_array.yml__expected_tset.json
- test-assets/yml/jekyll_ecommerce.yml
- test-assets/yml/jekyll_ecommerce.yml__expected_tset.json
Empty nodes were not handled correctly.
> Fix YML Crash

- README.md
- src/index.ts
- src/util/extract-version.ts
- test-assets/doc-assets/help_reference.txt
- test/e2e-win/version.test.ts
- test/e2e/help.test.ts
- test/setup/run-commander.test.ts
> -v, --version

- sample-scripts/yaml/attranslate-cache_from-en_to-yaml_src-en_ecommerce.yml.json
- sample-scripts/yaml/de_ecommerce.yml
- sample-scripts/yaml/en_ecommerce.yml
- sample-scripts/yaml/es_ecommerce.yml
- src/core/translate-cli.ts
- src/file-formats/common/format-cache.ts
- src/file-formats/yaml/yaml-generic.ts
- src/file-formats/yaml/yaml-manipulation.ts
- test-assets/yml/country_array.yml__expected_tset.json
- test-assets/yml/jekyll_ecommerce.yml
- test-assets/yml/jekyll_ecommerce.yml__expected_tset.json
Major improvement of YML tree traversal
> Preserve YML Comments and Whitespaces

- package.json
- sample-scripts/android/app/src/main/res/values-de/strings.xml
- sample-scripts/android/app/src/main/res/values-es/strings.xml
- sample-scripts/android/app/src/main/res/values-es/strings.xml_modified.xml
- sample-scripts/android/app/src/main/res/values/strings.xml
- src/file-formats/android-xml/xml-read.ts
- src/file-formats/android-xml/xml-write.ts
- test-assets/android-xml/advanced.xml
- test-assets/android-xml/plurals.xml
- test/e2e/scripts-android-ios.test.ts
- test/file-formats/simple-read-write.test.ts
- yarn.lock
https://github.com/fkirc/attranslate/issues/21
> Preserve XML Comments

- .github/workflows/ci.yml
`attranslate` has a few shaky dependencies that might be insourced if needed.
This PR tests the availability of required dependencies.
> Test Artifact Availability

- .github/workflows/ci.yml
Historically, `attranslate` had problems with a bad launch time due to https://github.com/googleapis/nodejs-translate/issues/595.
Those problems have been fixed with the help of "dynamic module imports", so this PR is meant as an additional regression test, in addition to the already existing perf-tests.
> Additional tests for launch time

- .github/workflows/ci.yml
- README.md
- src/core/core-util.ts
- test/e2e/scripts-json-multi.test.ts
- test/e2e/translate-modified.test.ts
> Adapt cache wording

- CHANGELOG.md
- README.md
- docs/SERVICE_CONFIG.md
- src/services/service-definitions.ts
- test-assets/doc-assets/help_reference.txt
- test/e2e-win/invalid-service-configs.test.ts
It was not even clear whether DeepL and Azure were working, so it might be better to remove them.
> Remove untested services

- CHANGELOG.md
- README.md
- src/core/core-definitions.ts
- src/core/translate-cli.ts
- src/core/translate-core.ts
- src/index.ts
- test-assets/doc-assets/help_reference.txt
- test/core/core-test-util.ts
- test/core/up-to-date-cache.test.ts
- test/e2e-win/invalid-options.test.ts
- test/e2e/e2e-common.ts
This did not work for all file formats, and it is perhaps not worth to explain it.
So it might be better to remove the option.
> Remove option --deleteStale=false

- CHANGELOG.md
- README.md
- docs/SERVICE_CONFIG.md
- src/services/service-definitions.ts
- test-assets/doc-assets/help_reference.txt
- test/e2e-win/invalid-service-configs.test.ts
Reverting parts of https://github.com/fkirc/attranslate/pull/123
> Reintroduce support for Azure service

- CHANGELOG.md
- src/services/azure-translator.ts
> Fix Azure response parsing

- README.md
- sample-scripts/json_advanced.sh
- test-assets/doc-assets/multi_json.snippet
> Simplify README

- sample-scripts/flutter/lib/l10n/intl_de.arb
- sample-scripts/flutter/lib/l10n/intl_es.arb
- sample-scripts/flutter/lib/l10n/intl_messages.arb
> Fix Flutter tests

- CHANGELOG.md
- README.md
- docs/SERVICE_CONFIG.md
- sample-scripts/flutter.sh
- sample-scripts/json_advanced.sh
- sample-scripts/json_simple.sh
- sample-scripts/json_simple_windows.bat
- src/index.ts
- src/services/service-definitions.ts
- src/services/zero-config-translate.ts
- test-assets/doc-assets/help_reference.txt
- test-assets/doc-assets/multi_json.snippet
- test-assets/doc-assets/simple_translate.snippet
- test/core/multi-lng.test.ts
- test/e2e-win/invalid-options.test.ts
> Zero-config: Speedup onboarding for new users of attranslate

- README.md
> Shorten README

- README-es.md
- docs/DEV_MANIFESTO-es.md
- docs/SERVICE_CONFIG-es.md
- docs/TOOL_COMPARISON-es.md
for all spanish speaking, better knowledge
> md files to spanish

- README-es.md
- README.md
> update spanish README

- README-es.md
- README.md
> update infos about OpenAI pricing (for cases of status code 429 OpenAI errors / "Too Many Requests")

- .github/workflows/ci.yml
- .gitignore
- package-lock.json
- package.json
- src/index.ts
- src/services/service-definitions.ts
- src/services/typechat.ts
- src/util/util.ts
- test/e2e/scripts-json-multi.test.ts
- test/test-util/test-util.ts
Servus!
Thanks for this awesome tool!
I added a new services which uses OpenAI and TypeChat to translate all strings.
New services:
- `typechat` -  translates a batch of 10 with a single prompt
- `typechat-manual` - feed the prompt into a LLM and copy the result  
Environment variables:
| Name | Default |
|--------|--------|
| OPENAI_API_KEY | required |
| OPENAI_MODEL | `text-davinci-003` |
| OPENAI_ENDPOINT | `https://api.openai.com/v1/chat/completions` |
| OPEN_AI_BATCH_SIZE | `10` |
| TYPECHAT_SCHEMA_NAME | `AppLocalizations` | 
| TYPECHAT_SCHEMA_COMMENT | `undefined` | 
I wasn't able to test it with the official OpenAI API, because I don't have an OpenAI API key. But it worked with a local [llama-cpp-python](https://github.com/abetlen/llama-cpp-python#web-server) web server.
A …
> Add TypeChat service

- sample-scripts/xml_generic.sh
> add typechat sample

- src/services/openai-translate.ts
- src/services/typechat.ts
Need update the model for openai service
please take a look [here](https://community.openai.com/t/openai-error-code-status-404/581481/1)
Best regards
Stefano Capitani
> Update model for openai service

- src/services/openai-translate.ts
Changing to the gpt-4o-mini-2024-07-18 model and with a prompt that generates more accurate results.
> Changing to the gpt-4o-mini-2024-07-18 model and with a prompt that generates more accurate results
